---
title: "R Notebook"
output: html_notebook
---

```{r}
library(gbm)

data <- read.csv("train.csv")
test_data <- read.csv("test.csv")
res_data <- read.csv("sample_submission.csv")

head(data)

summary(data)
```

```{r}
custom_threshold <- 0.1  #%
data_filtered <- data[, colMeans(is.na(data)) <= custom_threshold]
```

```{r}
convertToFactors <- function(data) {
  # Identify columns with categorical data
  cat_columns <- sapply(data, function(col) is.factor(col) || is.character(col))

  # Convert identified columns to factors
  data[, cat_columns] <- lapply(data[, cat_columns], as.factor)
  
  return(data)
}

data_factor = convertToFactors(data_filtered)
```


```{r}
# Assuming Sale_Price is a numeric variable in your data frame
library(ggplot2)

# Histogram
ggplot(data_filtered, aes(x = SalePrice)) +
  geom_histogram(binwidth = 50000, fill = "blue", color = "black", alpha = 0.7) +
  labs(title = "Distribution of Sale Price", x = "Sale Price", y = "Frequency")

# Density plot
ggplot(data_filtered, aes(x = SalePrice)) +
  geom_density(fill = "blue", color = "black", alpha = 0.7) +
  labs(title = "Density Plot of Sale Price", x = "Sale Price", y = "Density")
#SalePrice distribution is positively skewed => gamma

#data_factor$SalePrice_log <- log1p(data_factor$SalePrice)
```


```{r}
num_samples = dim(data_factor)[1]
sampling.rate = 0.8
training <- sample(1:num_samples, sampling.rate * num_samples, replace=FALSE)
trainingSet <- data_factor[training, ]
testing <- setdiff(1:num_samples,training)
testingSet <- data_factor[testing, ]

print(trainingSet)
trainingfeatures <- subset(trainingSet, select=-c(SalePrice))
print
# Get the labels of the training set
traininglabels <- trainingSet$SalePrice
# Get the features of the testing set
testingfeatures <- subset(testingSet, select = -c(SalePrice))
```






```{r}
set.seed(123)

# train GBM model
gbm.fit <- gbm(
  formula = traininglabels ~ . -c(SalePrice),
  data = trainingSet,
  distribution = "gaussian",
  n.trees = 5000,
  shrinkage = 0.1,
  interaction.depth = 3,
  n.minobsinnode = 10,
  cv.folds = 10
  )  

best <- which.min(gbm.fit$cv.error)

```

```{r}
prediction <- predict(gbm.fit, testingSet)
error = prediction - (testingSet$SalePrice)
mse = mean(error^2)
print(mse)
print(sqrt(mse))
```

```{r}
custom_threshold <- 0.1  #%
test_filtered <- test_data[, colMeans(is.na(test_data)) <= custom_threshold]

convertToFactors <- function(data) {
  # Identify columns with categorical data
  cat_columns <- sapply(data, function(col) is.factor(col) || is.character(col))

  # Convert identified columns to factors
  data[, cat_columns] <- lapply(data[, cat_columns], as.factor)

  return(data)
}

data_factor = convertToFactors(test_filtered)

prediction2 <- predict(gbm.fit, data_factor)
#error2 = prediction2-res_data$SalePrice
print(sqrt(mean(error2^2)))
```

